### PR TITLE
[WIP] Allow using external image interrogator for generating tags

### PR DESCRIPTION
**Pull request by fake-name**
This is a WIP for using an external (python) service to run any of  an assortment of tagging networks.

This is heavily inspired by the autotagger plugin for the automatic1111 stablediffusion web-ui: https://github.com/picobyte/stable-diffusion-webui-wd14-tagger

I really wanted to not have the external python service dependency, but replicating all the great python NN tooling in C# is way beyond my skillset, particularly because I barely know C# at all.

The python service and C# talk over a very, very simple gRPC interface. All the original functionality is also preserved, I'm just re-purposing the right-most column as controlled by a settings flag.

This PR is mostly because I'm not sure if this is something that you'd be interesting in mainlining or not. I also want to spend some time cleaning up the UI  layout hierarchy, but I'd like to make sure that's something you're interested in before doing more there.

### CODE REVIEW

**Comment by starik222** [comment]
Hello, thanks for your work! The built-in tag auto-generation function is really needed, and I have been thinking for a long time about how to implement it. I was only able to implement WD Tagger in C#, but I couldn’t implement BLIP, so I shelved it. Using Python is not very convenient, since you need to pre-configure it and run it separately, but having the function of auto-generating tags in the editor itself is great.
I did not see any problems with the Python code, but the C# code is not clear and does not work. In addition, I would not like to tie auto-generation of tags to the settings. The auto-generation feature should be more accessible. I understand that this is more of a presentation than a fully working code. So I'll accept your pull request, but I'll roll back most of the C# code and implement that part myself. I hope you won't be against such changes?

**Comment by fake-name** [comment]
Yeah, I hadn't finished the C# code by the point I opened the PR (that's why the [WIP] tag).

The current code in my fork does fully work, though there's probably some bugs in how the way I'm overriding the right-hand tag window.

I'm completely fine with you rewriting anything I did, though the C# code of mine is probably particularly bad. I have quite a bit of python and C++ experience, but this is nearly the first time I've touched C#.

Using my hacked-up version, I would propose changing the gRPC API slightly. Currently, the gRPC API has you specifying one tagging network to use. However, I often like to use multiple networks, so I think instead of taking a string parameter that specifies a single network, rather having it take a list of strings that each specify a network to query.

You want me to open a separate PR with just the python bits?

**Comment by fake-name** [comment]
More comments: A bunch of networks provide a confidence value for each tag (in the range of 0..1). This is something that really _should_ be exposed, but it's not done yet. You also want to be able to configure the minimal confidence threshold. I think I pushed that to the python, for no particular reason. I should really revert that too. I'm also assigning a stand-in value of '1' for all interrogators that don't assign a confidence, that should probably be at least re-considered as well.

**Comment by starik222** [comment]
> You want me to open a separate PR with just the python bits?

Yes, it would be nice. And I would like to ask you to fix a serious problem in the recognizer service. The problem is that each generation the service connects to the Internet and checks for the presence of a model and downloads a data dictionary. Once you turn off the Internet, the service stops working, even if there is cached data.
`DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/selected_tags.csv HTTP/1.1" 200 0
...
DEBUG:urllib3.connectionpool:Resetting dropped connection: huggingface.co
...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): huggingface.co:443
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /SmilingWolf/wd-v1-4-moat-tagger-v2/resolve/main/selected_tags.csv HTTP/1.1" 200 0`
 This not only creates dependence on the Internet, but also generates unnecessary traffic and slows down the service. I identified this problem on the WD model, I haven’t tested it on others, but judging by the code, others will also have this problem.

**Pull request closed without merging**
